/**
 * Author: Monayem Hossain Limon
 * GitHub: https://github.com/Limon00001
 * Date: 26 Apr, 2025
 * @copyright 2025 monayem_hossain_limon
 */

// External imports
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

// Internal imports
import AppSidebar from '@/components/AppSidebar';
import Navbar from '@/components/Navbar';
import { ThemeProvider } from '@/components/providers/ThemeProvider';

// Styles
import './globals.css';

// Fonts
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AppSidebar />
          <main className="w-full">
            <Navbar />
            <div className="px-4">
              {/* Page Content */}
              {children}
            </div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
